# Generated by Django 5.2 on 2025-05-05 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_messages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("message_sent_dt", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="messagesubscriber",
            name="last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="messagesubscriber",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("archived", "Archived"),
                ],
                default="active",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="messagesubscriber",
            name="subscriber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="messagesubscriber",
            constraint=models.UniqueConstraint(
                fields=("subscriber", "message_thread"), name="thread_subscriber"
            ),
        ),
        migrations.AddField(
            model_name="messagemessage",
            name="message_thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user_messages.messagethread",
            ),
        ),
        migrations.AddField(
            model_name="messagemessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
